org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# 环境属性
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17.20
fabric_api_version=0.159.0+26.2

# 模组属性
mod_id=dmonsters
mod_name=Deadly Monsters
mod_license=MIT
mod_version=1.0-26.2
mod_group_id=com.dmonsters
